### PR TITLE
Globalize functions to API for external use.

### PR DESCRIPTION
**Pull request by GreenXenith**
Puts most functions inside `sban` table for other mods to use.

### CODE REVIEW

**Comment by GreenXenith** [comment]
@shivajiva101 please let me know which ones shouldnt/should be globalized.

**Comment by shivajiva101** [comment]
If you look [here](https://github.com/shivajiva101/sban/blob/api/init.lua#L1612) you can see this is already being worked on. 

I don't think it's a good idea to allow anything other than reading the data outside of the ban functions and any exposed functions need to validate the incoming params for safety. For those reasons I prefer my solution.

**Comment by GreenXenith** [comment]
Wait. What?
~~I just cloned it today and I dont see that at all.~~
EDIT: Oh, different branch.

**Comment by GreenXenith** [comment]
@shivajiva101 that hasn't been updated for 6 months. If its being worked on then please get it pushed or something.

**Comment by shivajiva101** [comment]
aye, just because I haven't merged it doesn't mean it's forgotten. I'm looking at scenarios to speed the db access up, as you can see that branch also has a structure change that reduce access times for the crucial prejoin ban check in a mature server with a large ban db

**Pull request closed without merging**
